import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("accessToken")?.value ?? "";
  const refreshToken = cookieStore.get("refreshToken")?.value ?? "";
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider initialSessionToken={{ accessToken, refreshToken }}>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
